### ISSUE TITLE
Create "eslint-config-honeycomb"

### ISSUE THREAD

**Issue by danielbayerlein** [danielbayerlein/honeycomb#36]
I think it makes sense if we create a linter package.

Support
- eslint-config-airbnb-base
- eslint-config-airbnb

Maybe one package is enough, see https://github.com/sindresorhus/eslint-config-xo.

**Comment by chrishelgert** [comment]
```yaml
rules:
 comma-dangle:
  - error
  - arrays: always-multiline
    objects: always-multiline 
    imports: always-multiline
    exports: always-multiline
    functions: never
```

discussion, what do we want for all honeycomb-projects
